### ─── Variables ─────────────────────────────────────────────
@baseUrl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc5NDE3NzU3LCJleHAiOjE3ODAwMjI1NTd9.jON3bHyyjCqB4ZLqufpJzfEMRGpOtiD-hYSXuwI8tBg

### ─── TEST 1 : Vérifier que le serveur tourne ───────────────
GET http://localhost:3000

### ─── TEST 2 : Inscription étudiant ────────────────────────
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "nom": "Avinirina",
  "prenom": "Lucie",
  "email": "admin@gmail.com",
  "mot_de_passe": "admin1234",
  "role": "admin"
}

### ─── TEST 3 : Inscription enseignant ───────────────────────
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "nom": "Monsieur",
  "prenom": "Bakari",
  "email": "bakari@gmail.com",
  "mot_de_passe": "bakari111",
  "role": "enseignant"
}

### ─── TEST 4 : Connexion admin ──────────────────────────────
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "mot_de_passe": "admin1234"
}

### ─── TEST 5 : Connexion étudiant ──────────────────────────
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "jocy@gmail.com",
  "mot_de_passe": "jocy2812"
}

### ─── TEST 6 : Email déjà utilisé (doit retourner 409) ─────
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "nom": "RAMALALATIANA",
  "prenom": "Jackie",
  "email": "jocy@gmail.com",
  "mot_de_passe": "Password123",
  "role": "etudiant"
}

### ─── TEST 7 : Mauvais mot de passe (doit retourner 401) ───
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "jocy@gmail.com",
  "mot_de_passe": "mauvaismdp"
}

### ─── TEST 8 : Champs manquants (doit retourner 400) ───────
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "nom": "RAMALALATIANA"
}


### ════════════════════════════════════════════════════════════
###  MODULE ÉQUIPEMENTS
### ════════════════════════════════════════════════════════════

### ─── TEST 9 : Lister tous les équipements ──────────────────
GET {{baseUrl}}/equipements
Authorization: Bearer {{token}}

### ─── TEST 10 : Filtrer par type ordinateur ─────────────────
GET {{baseUrl}}/equipements?type=ordinateur
Authorization: Bearer {{token}}

### ─── TEST 11 : Filtrer par statut disponible ───────────────
GET {{baseUrl}}/equipements?statut=Disponible
Authorization: Bearer {{token}}

### ─── TEST 12 : Détail d'un équipement ─────────────────────
GET {{baseUrl}}/equipements/1
Authorization: Bearer {{token}}

### ─── TEST 13 : Statistiques équipements ────────────────────
GET {{baseUrl}}/equipements/stats
Authorization: Bearer {{token}}

### ─── TEST 14 : Créer un équipement (admin) ─────────────────
POST {{baseUrl}}/equipements
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nom": "PC_09",
  "type": "ordinateur",
  "numero_serie": "SN-PC-009",
  "date_acquisition": "2024-01-10",
  "statut": "Disponible",
  "description": "Nouveau poste de travail"
}

### ─── TEST 15 : Modifier un équipement (admin) ──────────────
PUT {{baseUrl}}/equipements/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Poste mis à jour"
}

### ─── TEST 16 : Changer le statut (admin) ───────────────────
PATCH {{baseUrl}}/equipements/3/statut
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "statut": "En maintenance"
}

### ─── TEST 17 : Supprimer un équipement (admin) ─────────────
DELETE {{baseUrl}}/equipements/9
Authorization: Bearer {{token}}

### ─── TEST 18 : Accès refusé sans token (doit retourner 401)
GET {{baseUrl}}/equipements

